name: Updates

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  generate_badge:
    runs-on: ubuntu-latest
    name: updates
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - uses: actions/setup-go@v4.0.0
        with:
          go-version: '^1.20'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install gRPC Go plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Run Update
        run: make update
      - name: Run Validate
        run: make validate
      - name: Commit the udpates (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Clement Jean'
            git config --global user.email 'Clement-Jean@users.noreply.github.com'
            git add *
            git commit -m "Autoupdates of dependencies"
            git push
          fi
