name: Updates

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  generate_badge:
    runs-on: ubuntu-latest
    name: badge_generation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Run Update
        run: make update
      - name: Run Validate
        run: make validate
      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Clement Jean'
            git config --global user.email 'Clement-Jean@users.noreply.github.com'
            git add *
            git commit -m "Autoupdates of dependencies"
            git push
          fi
